Django-seed custom_seed code 및 docs 수정
PNU-AID/AID_Backend_v2 pull request #23
Opened 2024-01-01 09:37 UTC by sihyeong671

## 설명
- 임시로 만들어진 User만 생성가능하도록 수정
- Docs 필요한 내용만 있도록 간단하게 변경

## 테스트 결과
PostgreSQL에서 잘 동작

2024-01-01 16:48 UTC, June222 requested changes
pyproject comment 한번만  봐주세요

2024-01-01 16:48 UTC, June222 commented on pyproject.toml
가현이 에러 때문에 이거하는 건 알겠는데 나는 django-seed에서 psycopg2 오류가 뜬 거라서 ([Link](https://pypi.org/project/django-seed/)) 이거는 지우면 안될 것 같은데 상관 없는거가?

2024-01-02 02:07 UTC, June222 commented on pyproject.toml
@sihyeong671

2024-01-02 13:43 UTC, sihyeong671 commented on pyproject.toml
django-seed는 안지웠어

2024-01-02 14:55 UTC, June222 commented on pyproject.toml
commit [19e4d16](https://github.com/PNU-AID/AID_Backend_v2/pull/23/commits/19e4d16a17bbe34bf839ace401722e488d69815d) 이거 왜 바꿈?

2024-01-03 05:52 UTC, June222 approved these changes
LGTM

2024-01-03 05:52 UTC, merged